services:
  - type: web
    name: telegram-camera-referral
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_TELEGRAM_ID
        value: "6002805119"

      - key: BASE_URL
        value: "https://aivideo-wn1o.onrender.com"
